- name: Preparing Workstation
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    - ansible_user: "andre"
  tasks:
    - block: # Personal
      - name: Personal Repos
        git:
          repo: git@github.com:aPedrotti/{{ item }}.git
          dest: /home/{{ ansible_user }}/code/github/{{ item }}
        loop:
          - abouts
          - ansible-linuxtips
          - apedrotti.github.io
          - apedrotti
          - argocd-poc
          - badges
          - DevOpsEngineerExpress
          - dotfiles
          - docker-descomplicando
          - eks-with-istio
          - gitlab
          - kubernetes
          - python-linuxtips
          - python-curso-em-video
          - sample-apps
          - shelling`
          - self 
          - take-home-assignment-main
          - terraforming
          - v01
          - vault-descomplicando



    - block: # DEVOPS
      - name: Devops
        git:
          repo: git@gitlab.gerdau.digital:devops/{{ item }}.git
          dest: /home/{{ ansible_user }}/code/gerdau/devops/{{ item }}
        loop:
          - a2a
          - gitlab-cicd
          - cronjobs
          - kubernetes-apps
          - platform-eks
          - platform-rancher
          - terraform-enterprise-helm
          - platform-rancher
          - helm-devops
          - helm-chart-sonarqube
          - terraform-enterprise-helm
      

    - block: # IT LABS
      - name: IT Labs
        git:
          repo: git@gitlab.gerdau.digital:ITLabs/{{ item }}.git
          dest: /home/{{ ansible_user }}/code/gerdau/itlabs/{{ item }}
        loop:
          - example-datalake
          - example-dotnet
          - example-nodejs
          - example-openjdk
          - example-package-npm
          - example-python
          - example-python-flask
          - example-terraform
          - example-react
          - example-react-cloudfront
          - external-logs-example
          - external-logs-example-m3-api
          

    - block: # TEMPLATES
      - name: Templates
        git:
          repo: git@gitlab.gerdau.digital:Templates/{{ item }}.git
          dest: /home/{{ ansible_user }}/code/gerdau/Templates/{{ item }}
        loop: 
          - datalake
          - ecs
          - jobs
          - mulesoft4
          - openshift
          - openshift-images

